kind = "web"
previewPath = "/"
title = "Grupo Starbank"
version = "1.0.0"
id = "artifacts/starbank"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19730

[services.development]
run = "pnpm --filter @workspace/starbank run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/starbank", "run", "build" ]
publicDir = "artifacts/starbank/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19730"
BASE_PATH = "/"
